CLASS zcl_abap_demo DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA : gv_name TYPE char100.
    DATA : gv_name1 TYPE char100.
    DATA : gv_name2 TYPE char100.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abap_demo IMPLEMENTATION.

ENDCLASS.
